name: Manage Branch Protection

on:
  schedule:
    - cron: "03 20 * * 3"
    - timezone: 'America/Mexico_City'

  workflow_dispatch:  # Permite activarlo manualmente también

jobs:
  manage-branch:
    runs-on: ubuntu-latest
    steps:
      - name: enable branch
        run: |
          echo "enabling branch"
          exit 0

      # - name: Set up variables
      #   id: vars
      #   run: |
      #     if [[ "$(date +%u)" == "3" ]]; then
      #       echo "ACTION=unprotect" >> $GITHUB_ENV
      #     elif [[ "$(date +%u)" == "5" ]]; then
      #       echo "ACTION=protect" >> $GITHUB_ENV
      #     else
      #       echo "No action needed today."
      #       exit 0
      #     fi

      # - name: Protect or unprotect the branch
      #   run: |
      #     OWNER="tu_usuario_o_org"
      #     REPO="tu_repositorio"
      #     BRANCH="main"
      #     TOKEN="${{ secrets.GH_PAT }}"

      #     if [[ "$ACTION" == "protect" ]]; then
      #       curl -X PUT \
      #         -H "Authorization: Bearer $TOKEN" \
      #         -H "Accept: application/vnd.github+json" \
      #         https://api.github.com/repos/$OWNER/$REPO/branches/$BRANCH/protection \
      #         -d '{
      #           "required_status_checks": null,
      #           "enforce_admins": true,
      #           "required_pull_request_reviews": {
      #             "required_approving_review_count": 1
      #           },
      #           "restrictions": null
      #         }'
      #     elif [[ "$ACTION" == "unprotect" ]]; then
      #       curl -X DELETE \
      #         -H "Authorization: Bearer $TOKEN" \
      #         -H "Accept: application/vnd.github+json" \
      #         https://api.github.com/repos/$OWNER/$REPO/branches/$BRANCH/protection
      #     fi
