name: Scheduled Pre-release (Mexico City Time)

on:
  schedule:
    # 00:00 CDMX es 06:00 UTC
    # Formato: Minuto Hora Día Mes Día-de-la-semana
    - cron: '03 04 * * *'
  workflow_dispatch: 

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Tag Name
        id: vars
        run: |
          # Configuramos la zona horaria para que el tag coincida con CDMX
          # v.YYYY.MM.DD-qa
          TAG_NAME="v.$(TZ='America/Mexico_City' date +'%Y.%m.%d')-qa"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: "Pre-release ${{ steps.vars.outputs.tag }}"
          body: |
            Release automático de QA generado el $(TZ='America/Mexico_City' date +'%Y-%m-%d %H:%M').
            Zona Horaria: America/Mexico_City
          draft: false
          prerelease: true
          target_commitish: main